# Generated by Django 5.0.7 on 2024-07-30 03:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 30, 3, 46, 22, 404611))),
                ('recent_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='posts.blog')),
                ('user_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
